#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
CONFIGFILES_DIR="$HOME/.system_configuration"
CONFIG_VARS="$CONFIGFILES_DIR/vars/env.vars"

# shellcheck disable=SC1090
source "$CONFIG_VARS"

# shellcheck disable=SC1091
source "$CONFIGFILES_DIR"/zsh/.zprofile

function install_oh_my_zsh() {
    echo -------------------
    echo "Installing Oh My ZSH..."
    echo -------------------

    if [[ -d "$HOME/.oh-my-zsh" ]]; then
        rm -rf "$HOME/.oh-my-zsh"
    fi

    eval "$GET_FILE $OHMYZSH_URL" | sh -s -- >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR"
}

function install_powerlevel10k() {
    echo -------------------
    echo "Installing Powerlevel10k..."
    echo -------------------
    if [[ ! -d "$ZSH_CUSTOM/themes/powerlevel10k" ]]; then
        git clone --depth=1 "$GH_URL/romkatv/powerlevel10k.git" "$ZSH_CUSTOM/themes/powerlevel10k" >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR"
    fi
}

function install_poetry() {
    echo -------------------
    echo "Installing Poetry..."
    echo -------------------
    eval "$GET_FILE https://install.python-poetry.org" | python3 - >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR: Installation error or Poetry is already installed."
    if [[ ! -d "$ZSH_CUSTOM/plugins/poetry" ]]; then
        mkdir -p "$ZSH_CUSTOM/plugins/poetry"
    fi
    
    poetry completions zsh > "$ZSH_CUSTOM/plugins/poetry/_poetry"
    
}

function install_pdm() {  
    echo -------------------
    echo "Installing PDM..."
    echo -------------------
    eval "$GET_FILE $PDM_URL" | python3 - >> "$LOG" 2>&1 && echo "Finished." || echo "ERROR: Installation error or PDM is already installed."
    if [[ ! -d "$ZSH_CUSTOM/plugins/pdm" ]]; then
        mkdir -p "$ZSH_CUSTOM/plugins/pdm"
    fi
    
    pdm completion zsh > "$ZSH_CUSTOM/plugins/pdm/_pdm"
}